// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function BrowseExcelFile() {
  return window['go']['main']['App']['BrowseExcelFile']();
}

export function GeneratePlotData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GeneratePlotData'](arg1, arg2, arg3, arg4);
}

export function GetExcelSheets(arg1) {
  return window['go']['main']['App']['GetExcelSheets'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenMessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenMessageDialog'](arg1, arg2, arg3);
}

export function ReadDatabaseDataFromExcel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadDatabaseDataFromExcel'](arg1, arg2, arg3, arg4);
}

export function ReadManualDataFromExcel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadManualDataFromExcel'](arg1, arg2, arg3, arg4);
}
